spring:
  application:
    # 服务名称
    name: itoken-eureka
  # 服务链路追踪Zipkin客户端
  zipkin:
    base-url: http://localhost:9411
  # 配置admin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # false是服务端 true是客户端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/